#!/bin/bash

# Copyright (c) 2021 by Philip Collier, github.com/AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# IMPORTANT!  SELECT the correct values here or you will destroy
# data you probably do not want to destroy!!!!
clear
echo "--- System Installer [RUN THIS WITH SUDO] ---"
echo -e "\nClone this live system to a partition you select."
echo -e "\n\nYou should format the partition or drive FIRST."
echo -e "\n\nHit [Enter] to install or [Ctrl + C] to quit..."
read line
clear

# list existing partitions
export PARTITION=$(fdisk -l | awk '{print $1}' | grep '^/dev/' | \
    fzf --header="Select Partition" | xargs -I {} echo "{}")
export MYMOUNT="/mnt"
export MYUUID=$(echo $(lsblk -no UUID $PARTITION))
export MYDEV=$(echo ${PARTITION//[0-9]/})

# quit if nothing selected
[[ -z "$PARTITION" ]] && echo "Exiting. No partition selected." && exit 0


echo -e "You have chosen partition:\n"
echo "     $PARTITION"
echo -e "\n\nAre you sure that you want to install
this filesystem onto $PARTITION?"
echo ""
echo 'Please answer "yes" or "no"'
read line
case "$line" in
    yes|Yes) echo "Okay, cloning will now begin!" ;;
    *) echo '"yes" not received, exiting the script.'; exit 0 ;;
esac

echo -e "\nWriting the filesystem, please stand by..."

# get the partition format
export FMT="$(df -T $PARTITION | grep "$PARTITION" | awk '{printf $2"\n"}')"

# mount the partition and clear the space
mount $PARTITION $MYMOUNT

# clone the running filesystem
rsync -aAxXHAWSP \
    --inplace \
    --delete \
    --info=progress2 \
    --numeric-ids \
    --exclude='/cdrom/*' \
    --exclude='/dev/*' \
    --exclude='/home/*/.gvfs' \
    --exclude='/home/*/.local/share/Trash' \
    --exclude='/home/*/.thumbnails' \
    --exclude='/lib/modules/*/volatile/.mounted' \
    --exclude='/media/*' \
    --exclude='/mnt/*' \
    --exclude='/proc/*' \
    --exclude='/run/*' \
    --exclude='/sys/*' \
    --exclude='/tmp/*' \
    --exclude='/var/lock/*' \
    --exclude='/var/run/*' \
    --exclude='*/Cache/*' \
    --exclude='*/cache/*' \
    --exclude='*/.cache/*' \
    / $MYMOUNT/  2>> ~/rsync.err

# install grub
grub-install --force --no-floppy --boot-directory=$MYMOUNT/boot $MYDEV

echo "UUID=$MYUUID /   $FMT    discard,noatime,nodiratime,errors=remount-ro 0 1" > $MYMOUNT/etc/fstab
cp /etc/hosts $MYMOUNT/etc/hosts

# Mount the newly written filesystem
echo 'Now entering the new filesystem...'
mount -o bind /run/ $MYMOUNT/run
mount --bind /dev $MYMOUNT/dev
mount --bind /proc $MYMOUNT/proc
mount --bind /sys $MYMOUNT/sys

# Chroot into the newly written filesystem
echo 'Updating Grub...'
chroot $MYMOUNT update-grub

echo 'Exiting...'
# Unmount after exiting the chroot
umount $MYMOUNT/sys
umount $MYMOUNT/proc
umount $MYMOUNT/dev
umount $MYMOUNT/run
